<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>Cringebot.MAUI</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>Cringebot.MAUI</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.cringebot.maui</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-android|AnyCPU'">
	  <ApplicationId>com.kra2008.cringebot</ApplicationId>
	  <DefineConstants>$(DefineConstants);__ANDROID__</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
	  <ApplicationId>com.kra2008.cringebot</ApplicationId>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
	  <ApplicationId>com.kra2008.cringebot</ApplicationId>
	  <DefineConstants>$(DefineConstants);__ANDROID__</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
	  <ApplicationId>com.kra2008.cringebot</ApplicationId>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <AndroidAsset Remove="Platforms\Android\Assets\AboutAssets.txt" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FreshMvvm.Maui" Version="0.0.4" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.60" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="PropertyChanged.Fody" Version="2.5.9" />
		<PackageReference Include="Syncfusion.Maui.Charts" Version="29.1.39" />
	</ItemGroup>

	<ItemGroup>
	  <AndroidAsset Update="Platforms\Android\Assets\Comic Sans MS.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </AndroidAsset>
	  <AndroidAsset Update="Platforms\Android\Assets\Emo.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </AndroidAsset>
	  <AndroidAsset Update="Platforms\Android\Assets\Plain Black.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </AndroidAsset>
	  <AndroidAsset Update="Platforms\Android\Assets\riseup.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </AndroidAsset>
	  <AndroidAsset Update="Platforms\Android\Assets\SBC Macaroni Regular.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </AndroidAsset>
	  <AndroidAsset Update="Platforms\Android\Assets\times.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </AndroidAsset>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Platforms\Android\AndroidManifest.xml">
	    <SubType>Designer</SubType>
	  </None>
	  <None Update="Platforms\iOS\Entitlements.plist">
	    <SubType>Designer</SubType>
	  </None>
	  <None Update="Platforms\iOS\Info.plist">
	    <SubType>Designer</SubType>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Resources\Styles\" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="App.xaml">
	    <SubType>Designer</SubType>
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\ChartPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\DetailsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\HelpPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\ImportExportPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\MainPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\SettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\StatsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
